---
language: node_js
node_js:
  - "6"

before_install:
- |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -E '^\.js|test/'
    then
      echo "No source or test files were update. Stopping CI build."
      exit
    fi

env:
  global:
    - SAUCE_USERNAME=autotrack
    - SAUCE_ACCESS_KEY=3256de84-6b60-4f8b-927f-a751ad917fc1
