---
language: node_js
node_js:
  - "6"

before_install:
- |
    echo "Checking $TRAVIS_COMMIT_RANGE for code file changes"
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE \
        | grep -E '(\.(js|yml|json)$)|(^(test|lib))/'
    then
      echo "No code files were update. Stopping CI build."
      exit
    fi

env:
  global:
    - SAUCE_USERNAME=autotrack
    - SAUCE_ACCESS_KEY=3256de84-6b60-4f8b-927f-a751ad917fc1
